using System;
using System.Collections.Generic;

namespace Generic.Data.Models
{
    public partial class TblVendorRegFormApproval
    {
        public int VendorApprovalId { get; set; }
        public int SupplierId { get; set; }
        public int FormId { get; set; }
        public string FormIdentificationName { get; set; }
        public string FormIdentificationPosition { get; set; }
        public string FormIdentificationPhoneNumber { get; set; }
        public string FormIdentificationWorkPhoneNumber { get; set; }
        public string FormIdentificationEmailAddress { get; set; }
        public string VendorCompanyName { get; set; }
        public string SubsidiaryCompanyName { get; set; }
        public string VendorHeadOfficeAddress { get; set; }
        public string VendorCompanyRegistrationNumber { get; set; }
        public string MainContactPersonName { get; set; }
        public string MainContactPersonPosition { get; set; }
        public string MainContactPersonPhone { get; set; }
        public string MainContactPersonWorkPhone { get; set; }
        public string MainContactPersonEmail { get; set; }
        public string BankReference { get; set; }
        public string ThirdPartyRefName { get; set; }
        public string ThirdPartyRefOrgAddress { get; set; }
        public string ThirdPartyRefContactNo { get; set; }
        public string ThirdPartyRefEmail { get; set; }
        public string VendorCompanyProfile { get; set; }
        public string VendorCompanyWebsiteAddress { get; set; }
        public string VendorNatureofBusiness { get; set; }
        public DateTime? VendorCompanyDateofCreation { get; set; }
        public string OwnershipMainShareholders { get; set; }
        public decimal? PercentageShareholding { get; set; }
        public string OwnershipNationality { get; set; }
        public string DirectServiceScopeMaterials { get; set; }
        public string DirectServiceScopeSubCategories { get; set; }
        public string TypicalSubContractedScopeProducts { get; set; }
        public string TypicalSubContractedScopeName { get; set; }
        public string TypicalSubContractedScopeAddress { get; set; }
        public string TypicalSubContractedScopeNationality { get; set; }
        public bool? TypicalSubContractedScopeIsLocal { get; set; }
        public string Cymfgffcity { get; set; }
        public string CymfgffplantEquipmentType { get; set; }
        public int? CymfgffplantEquipmentNumber { get; set; }
        public string Cymfgffutilization { get; set; }
        public decimal? CymfgfffactoryArea { get; set; }
        public string SpdirectServiceScopeService { get; set; }
        public string SpdirectServiceScopeServiceDetails { get; set; }
        public string SpofficeServiceCenterCity { get; set; }
        public string SpofficeServiceCenterCountry { get; set; }
        public string SpsubContractedServices { get; set; }
        public decimal? SpsubContractedServicesPercOutsourced { get; set; }
        public string SpsubContractorName { get; set; }
        public string SpsubContractorAddress { get; set; }
        public string SpsubContractorNationality { get; set; }
        public bool? SpsubContractorIsLocal { get; set; }
        public string AdforeignCompanyName { get; set; }
        public string AdforeignCompanyProductSupplied { get; set; }
        public string AdforeignCompanyStatus { get; set; }
        public string AdforeignCompanyOther { get; set; }
        public string VendorOrganizationChart { get; set; }
        public string VendorMissionVisionStatement { get; set; }
        public string KnowledgeofDgssystemsContractNo { get; set; }
        public string KnowledgeofDgssystemsProdEquServ { get; set; }
        public DateTime? KnowledgeofDgssystemsStartDate { get; set; }
        public string KnowledgeofDgssystemsDgsref { get; set; }
        public string VendorMainCustomerName { get; set; }
        public string VendorMainCustomerCountry { get; set; }
        public int? VendorMainCustomerValueYear { get; set; }
        public string VendorMainCustomerValue { get; set; }
        public string VendorCompanyDepartment { get; set; }
        public int? VendorCompanyNoofStaff { get; set; }
        public int? VendorCompanyNoofContractStaff { get; set; }
        public int? VendorCompanyNoofExpatriates { get; set; }
        public string CodeofConduct { get; set; }
        public string StaffTrainingPolicy { get; set; }
        public string StaffTrainingPolicyThirdPartyAudit { get; set; }
        public string FinancialAuditorName { get; set; }
        public string FinancialAuditorAddress { get; set; }
        public string FinancialAuditorContactNumber { get; set; }
        public string IsListedStockMarket { get; set; }
        public string QualityPolicy { get; set; }
        public string ProductQualityManagement { get; set; }
        public string QualityManagement { get; set; }
        public string QualityManagerName { get; set; }
        public string QualityManagerEmail { get; set; }
        public string QualityManagerPhoneNumber { get; set; }
        public string QualityManagerWorkPhoneNo { get; set; }
        public string QualityManagerFaxNumber { get; set; }
        public string QualityCertificationName { get; set; }
        public string QualityCertificationCertOrganization { get; set; }
        public DateTime? QualityCertficationValidityDate { get; set; }
        public string HealthSafetyEnvironmentPolicy { get; set; }
        public string HsethirdPartyAudit { get; set; }
        public string HsemanagerName { get; set; }
        public string HsemanagerEmail { get; set; }
        public string HsephoneNumber { get; set; }
        public string HseworkPhoneNumber { get; set; }
        public string HsefaxNumber { get; set; }
        public string HsecompanyKpi { get; set; }
        public string HsecompanyYearN1results { get; set; }
        public string HsestaffTrainingPolicy { get; set; }
        public string HsecertificationName { get; set; }
        public string HsecertificationCertAuthority { get; set; }
        public DateTime? HsecertficationValidityDate { get; set; }
        public string CorporateDistinctives { get; set; }
        public string CsrsocRespEthHumanLaborLaws { get; set; }
        public string VendorThirdPartySocialAudit { get; set; }
        public string VendorFraudMalpracticePolicy { get; set; }
        public int? ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string VendorCorporateAffairsCommisionNo { get; set; }
        public string FinancialStatementTaxIdnumber { get; set; }
        public string FinancialStatementYear1 { get; set; }
        public string FinancialStatementYear2 { get; set; }
        public string FinancialStatementYear3 { get; set; }
        public string StockMarketInfo { get; set; }
        public int? BusinessExFinancialTurnover { get; set; }
        public DateTime? BusinessExRegistrationDate { get; set; }
        public string BusinessExCompanyWorkedWith { get; set; }
        public string BusinessExTimeFrame { get; set; }
        public string BusinessExTransactionReference { get; set; }
        public string BusinessExScopeCovered { get; set; }
        public string BusinessExHasContinuityPolicy { get; set; }
        public string BusinessExContinuityPolicy { get; set; }
        public string VendorUsername { get; set; }
        public DateTime? FormIdentificationDate { get; set; }
        public bool? VendorIsForeign { get; set; }
    }
}
